### ISSUE TITLE
LSP Inactive  csharp

### ISSUE THREAD

**Issue by puristinsanity** [ChristianChiarulli/nvcode#4621]
### Problem description

LSP Inactive windows csharp

### LunarVim version

master-85ccca97

### Neovim version (>= 0.9.1)

0.10.2

### Operating system/version

Windows 11 

### Affected language servers

csharp servers

### Actual behavior

LSP Inactive

### support info

```console
#:LspInfo
 Language client log: C:\Users\username\AppData\Local\nvim-data/lsp.log
 Detected filetype:   cs
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: 
```
```console
#:Lsp

Buffer info
* filetype:                cs
* bufnr:                   1
* treesitter status:       active

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, ast_grep, azure_pipelines_ls, basedpyright, biome, bzl, css_variables, cssmodules_ls, custom_elements_ls, denols, docker_compose_language_service, dprint, elp, ember, emmet_language_server, emmet_ls, eslint, fennel_language_server, gitlab_ci_ls, glint, glslls, golangci_lint_ls, gradle_ls, graphql, harper_ls, hdl_checker, hydra_lsp, htmx, java_language_server, jedi_language_server, lexical, ltex, lwc_ls, mdx_analyzer, neocmake, nim_langserver, omnisharp, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, rubocop, ruby_lsp, ruff_lsp, snyk_ls, solang, solc, solidity_ls, solidity_ls_nomicfoundation, sorbet, somesass_ls, sourcery, spectral, sqlls, sqls, standardrb, stimulus_ls, stylelint_lsp, svlangserver, swift_mesonls, templ, tflint, tinymist, unocss, vale_ls, vacuum, verible, v_analyzer, vtsls, vuels]

Formatters info
* Active: 
* Supported: [astyle, clang_format, csharpier, uncrustify]

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

### logs

```console
[START][2024-11-07 18:09:25] LSP logging initiated
[ERROR][2024-11-07 18:09:25] .../vim/lsp/rpc.lua:770	"rpc"	"pwsh"	"stderr"	"\27[31;1m&: \27[31;1mThe term 'C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\powershell-editor-services/PowerShellEditorServices/Start-EditorServices.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.\27[0m\r\n"
[ERROR][2024-11-07 18:09:25] .../vim/lsp/rpc.lua:770	"rpc"	"pwsh"	"stderr"	"\27[31;1m\27[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.\27[0m\r\n"
[ERROR][2024-11-07 18:10:32] .../vim/lsp/rpc.lua:770	"rpc"	"pwsh"	"stderr"	"\27[31;1m&: \27[31;1mThe term 'C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\powershell-editor-services/PowerShellEditorServices/Start-EditorServices.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.\27[0m\r\n"
[ERROR][2024-11-07 18:10:32] .../vim/lsp/rpc.lua:770	"rpc"	"pwsh"	"stderr"	"\27[31;1m\27[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.\27[0m\r\n"
[WARN][2024-11-07 18:10:47] ...lsp/handlers.lua:625	"OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | "
[WARN][2024-11-07 18:12:58] ...lsp/handlers.lua:625	"OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | "
[WARN][2024-11-07 18:12:59] ...m/lsp/client.lua:1025	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-11-07 18:12:59] ...lsp/handlers.lua:623	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:595:48)\n    at handleMessage (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:432:20)\n    at Immediate.<anonymous> (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:402:30)\n    at process.processImmediate (node:internal/timers:476:21)"
[START][2024-11-07 19:42:30] LSP logging initiated
[WARN][2024-11-07 19:42:30] ...m/lsp/client.lua:1025	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-11-07 19:42:30] ...lsp/handlers.lua:623	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:595:48)\n    at handleMessage (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:432:20)\n    at Immediate.<anonymous> (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:402:30)\n    at process.processImmediate (node:internal/timers:476:21)"
[START][2024-11-07 20:03:16] LSP logging initiated
[WARN][2024-11-07 20:03:16] ...m/lsp/client.lua:1025	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-11-07 20:03:16] ...lsp/handlers.lua:623	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:595:48)\n    at handleMessage (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:432:20)\n    at Immediate.<anonymous> (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:402:30)\n    at process.processImmediate (node:internal/timers:476:21)"
[START][2024-11-11 17:38:00] LSP logging initiated
[ERROR][2024-11-11 17:38:00] .../vim/lsp/rpc.lua:770	"rpc"	"C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\bin\\zls.CMD"	"stderr"	"info : ( main ): Starting ZLS 0.13.0 @ 'C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\zls\\zls.exe'\n"
[ERROR][2024-11-11 17:38:00] .../vim/lsp/rpc.lua:770	"rpc"	"C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\bin\\zls.CMD"	"stderr"	"info : (server): Client is 'Neovim-0.10.2+g8b9864200'\ninfo : (server): No config file zls.json found. This is not an error.\n"
[ERROR][2024-11-11 17:38:00] .../vim/lsp/rpc.lua:770	"rpc"	"C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\bin\\zls.CMD"	"stderr"	"info : (server): Set config option 'builtin_path' to 'C:\\Users\\username\\AppData\\Local\\Temp\\zls\\builtin.zig'\ninfo "
[ERROR][2024-11-11 17:38:00] .../vim/lsp/rpc.lua:770	"rpc"	"C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\bin\\zls.CMD"	"stderr"	": (server): Set config option 'zig_lib_path' to 'C:\\Users\\username\\AppData\\Local\\Microsoft\\WinGet\\Packages\\zig.zig_Microsoft.Winget.Source_8wekyb3d8bbwe\\zig-windows-x86_64-0.13.0\\lib'\ninfo : (server): Set config option 'zig_exe_path' to 'C:\\Users\\username\\AppData\\Local\\Microsoft\\WinGet\\Packages\\zig.zig_Microsoft.Winget.Source_8wekyb3d8bbwe\\zig-windows-x86_64-0.13.0\\zig.exe'\ninfo : (server): Set config option 'build_runner_path' to 'C:\\Users\\username\\AppData\\Local\\Temp\\zls\\build_runner\\21872970afd69e48a0847077e5196711\\build_runner.zig'\ninfo : (server): Set config option 'global_cache_path' to 'C:\\Users\\username\\AppData\\Local\\Temp\\zls'\n"
[START][2024-11-11 17:56:40] LSP logging initiated
[WARN][2024-11-11 17:56:40] ...lsp/handlers.lua:625	"OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | "
[START][2024-11-11 18:26:22] LSP logging initiated
[WARN][2024-11-11 18:26:22] ...lsp/handlers.lua:625	"OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | "
[START][2024-11-11 18:26:38] LSP logging initiated
[WARN][2024-11-11 18:26:38] ...lsp/handlers.lua:625	"OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | "
[START][2024-11-11 18:29:28] LSP logging initiated
[WARN][2024-11-11 18:29:28] ...lsp/handlers.lua:625	"OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | "
[START][2024-11-11 18:35:16] LSP logging initiated
[WARN][2024-11-11 18:35:16] ...lsp/handlers.lua:625	"OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | "
[START][2024-11-11 19:12:39] LSP logging initiated
[WARN][2024-11-11 19:12:39] ...m/lsp/client.lua:1025	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-11-11 19:12:39] ...lsp/handlers.lua:623	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:595:48)\n    at handleMessage (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:432:20)\n    at Immediate.<anonymous> (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:402:30)\n    at process.processImmediate (node:internal/timers:476:21)"
[START][2024-11-11 20:38:25] LSP logging initiated
[WARN][2024-11-11 20:38:25] ...m/lsp/client.lua:1025	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-11-11 20:38:25] ...lsp/handlers.lua:623	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:595:48)\n    at handleMessage (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:432:20)\n    at Immediate.<anonymous> (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:402:30)\n    at process.processImmediate (node:internal/timers:476:21)"
[WARN][2024-11-11 20:54:58] ...m/lsp/client.lua:1025	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-11-11 20:54:58] ...lsp/handlers.lua:623	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:595:48)\n    at handleMessage (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:432:20)\n    at Immediate.<anonymous> (C:\\Users\\username\\AppData\\Roaming\\nvim-data\\mason\\packages\\json-lsp\\node_modules\\vscode-langservers-extracted\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:402:30)\n    at process.processImmediate (node:internal/timers:476:21)"
```

**Comment by puristinsanity** [comment]
default server (csharpls) could not download due to ssl issues which manifested in nuget. changed server in cs.lua to omnifunc and now it works good.

wish i knew how to start server of my choosing within editor. if anybody can tell me how i would appreciate.
