### ISSUE TITLE
Lvim crashes when LSP preview is shown

### ISSUE THREAD

**Issue by wildchild04** [ChristianChiarulli/nvcode#4624]
### Problem description

After loading a buffer and starting to type, at some point, most of the time when the lsp preview is rendered, lvim freezes 
This issue is mostly with elixir files, but I also had the issue while changing the lvim config with the lua lsp working, the logs show the warning `Unable to expand macro`

thanks in advance

### LunarVim version

master-85ccca9

### Neovim version (>= 0.9.1)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.172787038

### Operating system/version

Ubuntu WSL2

### Affected language servers

elixirls

### Steps to reproduce

After the buffer is loaded, and the LSP starts, as soon I the preview dialog appear, for example with atoms lvim freezes, see video attached 

### Actual behavior

Lvim  freezes

### support info

```console # :lspinfo

Language client log: /home/wildchild/.local/state/lvim/lsp.log
 Detected filetype:   elixir
 
 1 client(s) attached to this buffer: 
 
 Client: elixirls (id: 1, bufnr: [13])
 	filetypes:       elixir, eelixir, heex, surface
 	autostart:       true
 	root directory:  /home/wildchild/elixir/todo_2nd
 	cmd:             /home/wildchild/.local/share/lvim/mason/bin/elixir-ls
 
 Other clients that match the filetype: elixir
 
 Config: tailwindcss
 	filetypes:         aspnetcorerazor, astro, astro-markdown, blade, clojure, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, gohtmltmpl, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte, templ
 	root directory:    Not found.
 	cmd:               /home/wildchild/.local/share/lvim/mason/bin/tailwindcss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: elixirls, tailwindcss, gleam
```
```console # :Lviminfo

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                elixir
* bufnr:                   13
* treesitter status:       active

Active client(s)
* name:                      elixirls
* id:                        1
* supported filetype(s):     [elixir, eelixir, heex, surface]
* attached buffers:          13
* root_dir pattern:          13
* capabilities:              workspaceSymbolProvider | selectionRangeProvider     | definitionProvider
                             referencesProvider      | documentFormattingProvider | implementationProvider
                             foldingRangeProvider    | hoverProvider
                             macroExpansion          | codeActionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, ast_grep, azure_pipelines_ls, basedpyright, biome, bzl, css_variables, cssmodules_ls, custom_elements_ls, denols, docker_compose_language_service, dprint, elp, ember, emmet_language_server, emmet_ls, eslint, fennel_language_server, gitlab_ci_ls, glint, glslls, golangci_lint_ls, gradle_ls, graphql, harper_ls, hdl_checker, hydra_lsp, htmx, java_language_server, jedi_language_server, lexical, ltex, lwc_ls, mdx_analyzer, neocmake, nim_langserver, omnisharp, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, rubocop, ruby_lsp, ruff_lsp, snyk_ls, solang, solc, solidity_ls, solidity_ls_nomicfoundation, sorbet, somesass_ls, sourcery, spectral, sqlls, sqls, standardrb, stimulus_ls, stylelint_lsp, svlangserver, swift_mesonls, templ, tflint, tinymist, unocss, vale_ls, vacuum, verible, v_analyzer, vtsls, vuels, elixirls]

Formatters info
* Active: 
* Supported: [mix, surface]

Linters info
* Active: 
* Supported: credo

Code actions info
* Active: 
```

### logs

```console
[START][2024-11-12 20:32:03] LSP logging initiated
[ERROR][2024-11-12 20:32:03] .../vim/lsp/rpc.lua:770	"rpc"	"/home/wildchild/.local/share/lvim/mason/bin/elixir-ls"	"stderr"	"Running /home/wildchild/.local/share/lvim/mason/packages/elixir-ls/launch.sh\nPreferred shell is zsh, relaunching\n"
[ERROR][2024-11-12 20:32:03] .../vim/lsp/rpc.lua:770	"rpc"	"/home/wildchild/.local/share/lvim/mason/bin/elixir-ls"	"stderr"	"Looking for ASDF install\nASDF install found in /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh, sourcing\n"
[ERROR][2024-11-12 20:32:04] .../vim/lsp/rpc.lua:770	"rpc"	"/home/wildchild/.local/share/lvim/mason/bin/elixir-ls"	"stderr"	"Installing ElixirLS release v0.24.1\n"
[ERROR][2024-11-12 20:32:04] .../vim/lsp/rpc.lua:770	"rpc"	"/home/wildchild/.local/share/lvim/mason/bin/elixir-ls"	"stderr"	"Running in /home/wildchild/elixir/todo_2nd\n"
[ERROR][2024-11-12 20:32:04] .../vim/lsp/rpc.lua:770	"rpc"	"/home/wildchild/.local/share/lvim/mason/bin/elixir-ls"	"stderr"	"Install complete\n"
[WARN][2024-11-12 20:32:05] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:17] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:17] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:17] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:19] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:21] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:21] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:21] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:22] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:24] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:25] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:25] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:25] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:25] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:25] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:27] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:28] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[WARN][2024-11-12 20:32:28] ...lsp/handlers.lua:625	"Unable to expand macro GenServer.__before_compile__/1: ** (ArgumentError) could not call Module.defines?/2 because the module Todo.Server is already compiled. Use Kernel.function_exported?/3 and Kernel.macro_exported?/3 to check for public functions and macros instead\n    (elixir 1.17.2) lib/module.ex:2350: Module.assert_not_compiled!/3\n    (elixir 1.17.2) lib/module.ex:1158: Module.defines?/2\n    (elixir 1.17.2) expanding macro: GenServer.__before_compile__/1\n    nofile: Todo.Server (module)\n"
[
```

### Screenshots

https://github.com/user-attachments/assets/e057a09e-c5b4-4dd8-8d21-95b5aa2aad44

![image](https://github.com/user-attachments/assets/732d7586-b04e-499e-a611-7ed404ba4ac2)

**Comment by kfirbreger** [comment]
I am experiencing similar problems, and I am working on a python codebase.

**Comment by CyberDogFK** [comment]
Same for lua files on macos

**Comment by joaospinto** [comment]
I also just started getting `lvim` freezes, although I haven't properly root-caused it (could be unrelated to this, but the last few messages make me suspect otherwise). I _think_ they happen when I press `d` to delete a selection in visual mode, mostly. Also strange that this would suddenly start happening; I don't recall having updated any related software.

**Comment by kfirbreger** [comment]
I followed the [instructions on updating Mason and the LSP servers](https://www.lunarvim.org/docs/configuration/language-features/language-servers) and the hanging went away. Might want to try this. I don't know what changed, since I also didn't update anything, but I did have some updates to the LSP servers that I could do.

Update:
Nope, its back again.

**Comment by Pger-Y** [comment]
I'm experiencing the same issue. When using the latest LunarVim with Neovim 0.10.2, the editor completely hangs whenever the completion popup appears. This occurs while editing both Python and Golang files on all my machines (both M1 and M2 Macs). The issue causes the CPU usage to spike to 100%, forcing me to force-quit Neovim. After downgrading to Neovim 0.10.1, the problem was resolved. I suspect it might be related to LSP communication with Neovim, though I'm not certain about the root cause.

**Comment by Pger-Y** [comment]
check this: https://github.com/neovim/neovim/issues/31163#issuecomment-2469978909

**Comment by wildchild04** [comment]
since I'm using WLS and I though this was a me problem, and also having my dot files and scripts to spin of a new VM, I deleted that one and created an other one, so I no longer have the freezing nvim issue, but it looks like the updating/reinstalling tree sitter might solve the issue. If someone has this issue take a look at:
https://github.com/neovim/neovim/issues/31163#issuecomment-2469978909
thanks @Pger-Y for the update
Closing this issue soon when, it would be cool if we get some updates from the folks that had the issue just to confirm that the issue is gone

**Comment by joaospinto** [comment]
My issue was exactly what @Pger-Y mentioned above, so it's definitely gone for me.

**Comment by wildchild04** [comment]
cool, thanks for the update @joaospinto 
closing this one 
thanks everyone!
